/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ['"JetBrains Mono"', '"IBM Plex Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
        serif: ['"Instrument Serif"', '"Newsreader"', '"Playfair Display"', "Georgia", "serif"],
        display: ['"Instrument Serif"', '"Newsreader"', '"Playfair Display"', "Georgia", "serif"],
        playfair: ['"Playfair Display"', "serif"],
        inter: ["Inter", "sans-serif"],
      },
      colors: {
        page: "#0C0B09",
        sidebar: "#0C0B09",
        card: "#0C0B09",
        "card-hover": "#141210",
        divider: "#29241B",
        "card-border": "#29241B",
        primary: "#ECE5D5",
        muted: "#8C8577",
        faint: "#4C4739",
        section: "#8C8577",
        "brand-green": "#5BA97C",
        "brand-red": "#D16A5B",
        "brand-gold": "#D1A92E",
        "brand-blue": "#7FB4FF",
        // Quantix Glass V2 Theme Tokens
        "glass-page": "#08090E",
        "glass-sidebar": "#0B0D14",
        "glass-card": "rgba(18, 21, 32, 0.65)",
        "glass-card-hover": "rgba(25, 30, 45, 0.8)",
        "glass-border": "rgba(255, 255, 255, 0.08)",
        "glass-border-glow": "rgba(255, 255, 255, 0.18)",
        "glass-accent-emerald": "#10B981",
        "glass-accent-rose": "#F43F5E",
        "glass-accent-amber": "#F59E0B",
        "glass-accent-indigo": "#6366F1",
      },
    },
  },
  plugins: [],
};
